### ISSUE TITLE
Chinese Translation added / 已新增中文翻译

### ISSUE THREAD

**Issue by HueLiu** [ATGH15102AFMLD/Linkbar#1]
I have send the .lc3 to you. If possible, add Chinese translation to the next update. Thank you.

------

如果有中文翻译需要的，在未更新前可先在这里下载[中文翻译文件](https://www.seekhue.com/linkbar)

**Comment by ATGH15102AFMLD** [comment]
Version 1.6.7  introducing new localization system. Simple and clear. Localization with DelLoc is deprecated. Thanks for the translation. It'll be added to the next release.
