### ISSUE TITLE
Would like to see a branch for 1.6.9 development here.

### ISSUE THREAD

**Issue by AltitudeApps** [ATGH15102AFMLD/Linkbar#11]
Subject says it all.  

I would like to do my own build, but I don't really want to mess around with the outdated 1.6.8 stuff.

**Comment by ATGH15102AFMLD** [comment]
Branch [1.6.9-beta](https://github.com/ATGH15102AFMLD/Linkbar/tree/1.6.9-beta). IDE Delphi 10.3.3 Community Edition. [Inline Variable Declaration](http://docwiki.embarcadero.com/RADStudio/Rio/en/Inline_Variable_Declaration) used.
If you have any further questions feel free.
