### ISSUE TITLE
Access violation error (when clicking Setting)

### ISSUE THREAD

**Issue by Obarda** [ATGH15102AFMLD/Linkbar#14]
Hi,

I'm using Linkbar version 1.6.8 and I **can't get access to "Settings"**.

Workflow:
1. Start Linkbar.exe or Linkbar64.exe
2. Right-click -> Settings
3. Choose Setting
4. Error message: **_Access violation at address 000000000040B83B in module 'Linkbar.64.exe'. Read of address 00000000000000FB._**
![ScreenHunter_32 Oct  17 20 31](https://user-images.githubusercontent.com/73034911/96349405-18bd0600-10b8-11eb-9717-e351c2ed4adb.jpg)

P.S I've tried Delete & Create the Linkbar and also downloading it again from the website, and nothing helps.

**Comment by ATGH15102AFMLD** [comment]
Hello,

Please to try version 1.6.9 (beta)
https://sourceforge.net/projects/linkbar/files/Version%201.6.9%20beta/

Thanks for using,
Linkbar

**Comment by Obarda** [comment]
Thank you, but I still get the same error even with 1.6.9 bet5:
![ScreenHunter_32 Oct  17 22 47](https://user-images.githubusercontent.com/73034911/96352283-c46f5180-10ca-11eb-973e-6ded75b7f69a.jpg)
![ScreenHunter_32 Oct  17 22 46](https://user-images.githubusercontent.com/73034911/96352284-c5a07e80-10ca-11eb-99fb-f6a25e05efd7.jpg)

**Comment by Obarda** [comment]
I'm using Win10

**Comment by ATGH15102AFMLD** [comment]
Hello,
Please run debug version of Linkbar and send me the error message again.
[Linkbar_1_6_9_beta_6_debug.zip](https://1drv.ms/u/s!ArRLDIr9g7QghmakJOKV8iWzYtd9?e=UoMf06) (6MB)

**Comment by Obarda** [comment]
Thank you . I got I think 30-40 error message, I couldn't capture them all
but I will send you some, pls tell me if its enough
[image: ScreenHunter_41 Oct. 25 01.10.jpg]
[image: ScreenHunter_46 Oct. 25 01.10.jpg]
[image: ScreenHunter_45 Oct. 25 01.10.jpg]
[image: ScreenHunter_44 Oct. 25 01.10.jpg]
[image: ScreenHunter_43 Oct. 25 01.10.jpg]
[image: ScreenHunter_42 Oct. 25 01.10.jpg]

**Comment by Obarda** [comment]
After hundreds of errors i gets this:
[image: image.png]

**Comment by Obarda** [comment]
I get hundreds of errors message when I try to start this Debug exe.
![ScreenHunter_46 Oct  25 01 22](https://user-images.githubusercontent.com/73034911/97094768-acff0e00-1660-11eb-9957-39cd5cdc7b12.jpg)
![ScreenHunter_46 Oct  25 01 10](https://user-images.githubusercontent.com/73034911/97094772-ad97a480-1660-11eb-9f92-e3ee247f3c63.jpg)
![ScreenHunter_45 Oct  25 01 10](https://user-images.githubusercontent.com/73034911/97094773-ae303b00-1660-11eb-94ba-45b439cfb4d9.jpg)
![ScreenHunter_44 Oct  25 01 10](https://user-images.githubusercontent.com/73034911/97094774-ae303b00-1660-11eb-84cf-8c1cae793c3f.jpg)
![ScreenHunter_43 Oct  25 01 10](https://user-images.githubusercontent.com/73034911/97094775-aec8d180-1660-11eb-8597-0a935b0c2082.jpg)
![ScreenHunter_42 Oct  25 01 10](https://user-images.githubusercontent.com/73034911/97094776-aec8d180-1660-11eb-9b9a-cd7595587e0a.jpg)
![ScreenHunter_41 Oct  25 01 10](https://user-images.githubusercontent.com/73034911/97094777-af616800-1660-11eb-8226-015ea67f77cb.jpg)

**Comment by ATGH15102AFMLD** [comment]
Messages with yellow triangle are not errors, but warnings about missing localization strings. I didn't include "Locale" folder in the archive or ask you to place the debug exe into the previous version folder before run it.
I'm ashamed. Thank you.

**Comment by Obarda** [comment]
Ok, I extracted your zip into the Linkbar folder in my program files, and started the debug.
Then I clicked on right-mouse and Setting, and I got this error:
![image](https://user-images.githubusercontent.com/73034911/97096218-2438a000-1669-11eb-8ca1-9176c4dd45ad.png)

**Comment by ATGH15102AFMLD** [comment]
Do you have same exception if click "Delete the linkbar..." from context menu?

**Comment by Obarda** [comment]
No. I can delete without an error.

**Comment by ATGH15102AFMLD** [comment]
This executable collects extended error info - [Linkbar64D_1_6_9_beta_6.zip](https://1drv.ms/u/s!ArRLDIr9g7QghmnVCT0rxeytHg6P?e=9SbaCt) (6MB).
Please run it, get the error, save a log file and send it to me. Log contains your system information. Don't post the log file here, email me linkbar@yandex.ru

**Comment by Obarda** [comment]
Just sent you the log. Thanks.

**Comment by Obarda** [comment]
@ATGH15102AFMLD  Thank you very much for fixing it !

**Comment by Obarda** [comment]
@ATGH15102AFMLD Can I download & install the new release from January (Version 1.6.9 general release)?
Or will it reproduce the issue we struggle with on last October, on my machine.

**Comment by ATGH15102AFMLD** [comment]
Yes. In the version 1.6.9 general release, this issue was fixed.

**Comment by Obarda** [comment]
> Yes. In the version 1.6.9 general release, this issue was fixed.

Thank you!
