### ISSUE TITLE
'Unable to create directory'

### ISSUE THREAD

**Issue by azev** [ATGH15102AFMLD/Linkbar#15]
I'm using linkbar with the command line:

`Linkbar64.exe -f linkbar.lbr`

When I go to settings and click Ok/Apply it shows the following message:

![s20201026131952](https://user-images.githubusercontent.com/6639188/97200002-6fe56980-178f-11eb-8b9b-9cdd65af7c96.png)

I think Linkbar should be **portable** by default. Please, make future versions use the **application folder** instead of windows user profile folder.

**Comment by ATGH15102AFMLD** [comment]
Remove white spaces between key an value

Linkbar64.exe -flinkbar.lbr

In the "New linkbar" dialog select "Anyone who uses this computer (all users)" and the profile will be created in the folder "Shared bars" near Linkbar.exe

**Comment by azev** [comment]
Thanks!
