### ISSUE TITLE
Capture of strange website connection

### ISSUE THREAD

**Issue by MapleCCC** [ATGH15102AFMLD/Linkbar#2]
Dear ATGH15102AFMLD,
Thank you for bringing such a useful software for us. Last night, GlassWire, the internet monitor software installed on my PC, had captured an internet connection launched by the linkbar process. And the destination website, as I recognize, belongs to the input method right now running on my PC(called Sogou input method). I love this app a lot, it's really helpful and boosts my productivity. God knows how I yearn for a software implementing multiple taskbar before. But it's just that this connection detected is so weird and I wonder why the internet connection is made, and especially, why would it try to connect to my input method's website? Would really appreciate it if you can explain some of my confusion.
The screen shot of GlassWire is attached as follow.

![image](https://user-images.githubusercontent.com/25131775/32386894-b212c7a8-c0fd-11e7-81b9-0bd86169c011.png)

**Comment by ATGH15102AFMLD** [comment]
Looks like a virus "Sogou". Executable files published on [SourceForge](https://sourceforge.net/projects/linkbar/) do not contain malicious code, verified by VirusTotal. Check your PC for viruses and be careful when downloading the Linkbar from other sites.
Thank you for using the Linkbar.
