### ISSUE TITLE
[Request] Activity indicator for running programs

### ISSUE THREAD

**Issue by Marrib** [ATGH15102AFMLD/Linkbar#21]
When a program is running, the Windows Taskbar indicates this by displaying an indicator under the application icon.

It would be great if Linkbar could do that, too. Because some applications are sitting in the Windows system tray when running, not in the Windows Taskbar. This makes it harder to see which apps are running and which are not. If Linkbar would show an indicator below the application icons, this would make it very easy to see at first glance, which apps are running and which are not.

**Comment by ATGH15102AFMLD** [comment]
Linkbar is just a quick launch app. I do not plan to add indicators of running applications, other system resources, and a plugin system. Unfortunately, you will have to look for an alternative application.
