### ISSUE TITLE
[Feature idea] Option to automatically increase Linkbar size and icon size when Windows 10 switches to Tablet Mode

### ISSUE THREAD

**Issue by Marrib** [ATGH15102AFMLD/Linkbar#23]
Windows 10 has an option in the system settings to turn on User Interface Enlargement when a device (like a Convertible or Tablet) switches from mouse/keyboard input mode to Tablet Mode. This mode switches the Taskbar from small size to the normal bigger size, for example, or adds a little bit more space between the icons in the Taskbar and between other user interface elements. That way the device can be operated more easily using Touch/Finger input.

It would be great if there was an option in the Linkbar preferences to adapt that Windows feature. Every time Windows switches to Tablet Mode, Linkbar should increase its size as well to a larger size with more space between the icons. The larger size and the increased space between the buttons should be customizable by the user, in such a way the the user can input number values how large Linkbar should be.

This should be, of course, optional so that users can turn automatic enlargement off if they don't want Linkbar to enlarge.

**Comment by ATGH15102AFMLD** [comment]
I'll see how this mode works and what can be done.

**Comment by Marrib** [comment]
So it seems that in the newly announced Windows 11 the dedicated Tablet mode will be removed. But it's funcationality remains: when switching to touch/tablet input mode, Windows 11 behaves similar: icons become bigger, spaces between items larger etc.
Source: https://www.digitaltrends.com/computing/5-ways-windows-11-will-revolutionize-windows-tablets

**Comment by ATGH15102AFMLD** [comment]
I implemented this feature to the version [1.7.0 beta 1](https://sourceforge.net/projects/linkbar/files/Version%201.7.0%20beta/).

**Comment by Marrib** [comment]
Cool. I guess this thread can be marked as resolved/closed then?

**Comment by ATGH15102AFMLD** [comment]
I would close with a commit.
