### ISSUE TITLE
[Feature idea] Icon magnification like macOS Dock.

### ISSUE THREAD

**Issue by Marrib** [ATGH15102AFMLD/Linkbar#24]
It would be great if Linkbar could get a magnification feature like masOS Dock has it (see screenshot), that can be turned of or on in the Linkbar preferences.

With such a feature users could set their Linkbar to a small, space saving icon size and still use it comfortably and always hit the right icons without erroneously clicking a wrong icon, because magnification helps hitting the right icon.

![maginfication](https://user-images.githubusercontent.com/40357209/116544472-7778fd00-a8ef-11eb-8fcd-a6adf7a97e1e.jpg)

**Comment by ATGH15102AFMLD** [comment]
Linkbar aims to be similar in design to a Windows 7/8/9 system app. I have no plans to add such animations or themes, at least until such animations appear in Windows. Unfortunately, you will have to look for an alternative application.
