### ISSUE TITLE
A little appearance problem when put taskbar on top and linkbar on left with autohide

### ISSUE THREAD

**Issue by 944705050** [ATGH15102AFMLD/Linkbar#3]
When I put windows' taskbar on top of the screen and put linkbar on the left with the feature `AutoHide`, the windows' taskbar would cover a part of linkbar.
~(Sorry for my bad English, Thanks)~

**Comment by ATGH15102AFMLD** [comment]
This is the default behavior for Windows. Both panels have the same right to be on top of each other. Therefore, if you click on the taskbar, it will overlap the Linkbar until the next redrawing of the Linkbar (click or select an item). If I find a solution, I will correct it.

**Comment by 944705050** [comment]
Maybe you can try to set a space on Linkbar to avoid overlapping the taskbar or being overlapped by it.

Thanks for Linkbar.
