### ISSUE TITLE
LINKBAR

### ISSUE THREAD

**Issue by JeanPierreNortje** [ATGH15102AFMLD/Linkbar#55]
I downloaded LINKBAR to create multiple Taskbars.
Amazing app. 
However the Taskbars  disappear when I restart my laptop and I have to set them up all over again.
I run Windows 11.
Please help.

**Comment by saqeelahmed** [comment]
use windows native method to make it open at startup everytime when you restart.

make a shortcut and put in startup folder of windows.

use win key + r to run shell:startup [opens startup folder]

paste shortcut into this opened folder and you are done

**Comment by JeanPierreNortje** [comment]
Hi Saqeelahmed thank you very much it works!

**Comment by JeanPierreNortje** [comment]
Hi Saqeelahmed thank you very much it works!

**Comment by JeanPierreNortje** [comment]
Hi Saqeelahmed thank you very much it works!

**Comment by JeanPierreNortje** [comment]
Thank you so much its working great!

 

 <https://bestbidonline.co.za/>

**Comment by saqeelahmed** [comment]
Can admin pin this or paragraph out at the top and have it visible as pinned so everyone can follow as to how to keep linkbar auto restart after windows is restarted or shutdown and restarted . A lot of people have asked this question. Any programmer can extend this program by coding the program to copy its shortcut into windows startup folder but then it will need to have install/ uninstall feature for full cleanup if undesired or unwanted the software.
