### ISSUE TITLE
Centralize icons?

### ISSUE THREAD

**Issue by Louco-Diamante** [ATGH15102AFMLD/Linkbar#9]
Any chance for centralized icon position?

**Comment by ATGH15102AFMLD** [comment]
[Linkbar 1.6.9 beta](https://sourceforge.net/projects/linkbar/files/Version%201.6.9%20beta/) has this option.

**Comment by Louco-Diamante** [comment]
![Screenshot_851](https://user-images.githubusercontent.com/58825381/91651427-e94c2e80-ea62-11ea-9cd4-96c79cf80b05.jpg)
Amazing! Its perfect now! Thank you

**Comment by ATGH15102AFMLD** [comment]
Thanks for using Linkbar.
